<?php
$z[0]=Array("pubdate","",195,241);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%d\",@me)";
$z[1]=Array("pubdate","",289,338);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%Y-%m\",@me)";
$z[2]=Array("arcurl","",475,490);
$z[2][4]=array();
$z[3]=Array("title","",499,513);
$z[3][4]=array();
$z[4]=Array("title","",515,529);
$z[4][4]=array();
$z[5]=Array("description","",576,626);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,250)";

?>