<div class="xm4 xb4 xs4 xl6 margin-large-bottom">
          <div class="pro-item">
           
            <div class="portfolio-img"><a href="[field:arcurl/]" title="[field:title/]" class="zoomimgs" style="background-image:url([field:litpic/])"></a></div>
            <p class="desc">[field:description function='cn_substr(@me,250)'/]...</p>
            <p class="more"><a href="[field:arcurl/]" >READ MORE ></a></p>
          </div>
        </div>