<div class="xl6 xs6 xm4">
                <div class="item item3"><a href="{dede:field name='typeurl'/}"  title="{dede:field name='typename'/}">
                  <div class="media-img"><img src="/style/images/s2.png" /></div>
                  <h3>{dede:field name='typename'/}</h3>
                  <div class="desc">{dede:field name='content'/}</div>
                  </a></div>
              </div>