<?php
$z[0]=Array("pubdate","",105,151);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%d\",@me)";
$z[1]=Array("pubdate","",191,240);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%Y-%m\",@me)";
$z[2]=Array("arcurl","",337,352);
$z[2][4]=array();
$z[3]=Array("title","",361,375);
$z[3][4]=array();
$z[4]=Array("title","",377,391);
$z[4][4]=array();
$z[5]=Array("description","",421,471);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,250)";

?>