<div class="xm4 xs6 xl6 margin-large-bottom text-center"><a href="[field:arcurl/]" title="[field:title/]">
                  <div class="media-img">
                    <div class="zoomimgs" style="background-image:url([field:litpic/])"></div>
                  </div>
                  <div class="content">
                    <h3>[field:title/]</h3>
                  </div>
                  </a></div>