<?php
$z[0]=Array("global","",280,302);
$z[0][4]=array();
$z[0][4]['name']="cfg_top";
$z[1]=Array("global","",922,943);
$z[1][4]=array();
$z[1][4]['name']="cfg_qq";
$z[2]=Array("global","",1047,1071);
$z[2][4]=array();
$z[2][4]['name']="cfg_weibo";
$z[3]=Array("global","",1435,1461);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",1694,1715);
$z[4][4]=array();
$z[4][4]['name']="cfg_sj";
$z[5]=Array("global","",1848,1869);
$z[5][4]=array();
$z[5][4]['name']="cfg_dh";
$z[6]=Array("global","",2002,2023);
$z[6][4]=array();
$z[6][4]['name']="cfg_dz";
$z[7]=Array("field","(@me==\"\")? @me=\" class='current'\":@me=\"\";",2306,2397);
$z[7][4]=array();
$z[7][4]['name']="typeid";
$z[7][4]['runphp']="yes";
$z[8]=Array("channelartlist","\r\n            <li {dede:field name='currentstyle'/}><a class=\"first-level\" href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}<span class=\"downward\"></span></a>\r\n              <ul class=\"drop-menu\">\r\n                {dede:channel type='son' noself='yes'}\r\n                <li><a href='[field:typelink/]' title=\"[field:typename/]\">[field:typename/]</a></li>\r\n                {/dede:channel}\r\n              </ul>\r\n            </li>\r\n            ",2459,2979);
$z[8][4]=array();
$z[8][4]['row']="10";
$z[8][4]['typeid']="top";

?>