<?php
$z[0]=Array("global","",280,302);
$z[0][4]=array();
$z[0][4]['name']="cfg_top";
$z[1]=Array("global","",1265,1286);
$z[1][4]=array();
$z[1][4]['name']="cfg_qq";
$z[2]=Array("global","",1390,1414);
$z[2][4]=array();
$z[2][4]['name']="cfg_weibo";
$z[3]=Array("field","(@me==\"\")? @me=\" class='current'\":@me=\"\";",1839,1930);
$z[3][4]=array();
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[4]=Array("channelartlist","\r\n            <li {dede:field name='currentstyle'/}><a class=\"first-level\" href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}<span class=\"downward\"></span></a>\r\n              <ul class=\"drop-menu\">\r\n                {dede:channel type='son' noself='yes'}\r\n                <li><a href='[field:typelink/]' title=\"[field:typename/]\">[field:typename/]</a></li>\r\n                {/dede:channel}\r\n              </ul>\r\n            </li>\r\n            ",1998,2518);
$z[4][4]=array();
$z[4][4]['row']="10";
$z[4][4]['typeid']="top";

?>